### Service du TD4
# 
# apiVersion: v1
# kind: Service
# metadata:
#   name: demo-service
# spec:
#   selector:
#     name: website
#   ports:
#   - port: 5000
#     targetPort: 80
#   type: ClusterIp
# 
# 
### Version template du même service
# Paramètres :
# - Port hôte
# - Port conteneur
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app.fullname" . }}-service
spec:
  selector:
    app: helm-demo
    {{- include "helm-app.labels" . | nindent 4 }}   
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  type: ClusterIP